title: "Mohammad Izadi Toopkanloo"
author: "Mohammad Izadi Toopkanloo"
description: "Amirkabir University of Technology"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: false               # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", title: Home Change, sidebaricon: home}
  - {file: "README.md", title: About me, sidebaricon: address-card}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:mohammad.izd@aut.ac.ir"}
  - {title: Github, icon: github, url: "https://github.com/Mohammadizadi76"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
